### PR TITLE
adding mt_deconv !

### PR DESCRIPTION
**Pull request by ThomasLecocq**
Adding a wrapper to the mt_deconv function available in the fortran library.
Test doesn't pass, not sure of the result file I found in the examples, might need to run the routine directly and get the output in order to compare. (visually they are very similar!)
Doc should be OK. Tutorial has been updated to include the reproduction of Figure 6 from the original publication.
mt_deconv

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
I don't know what the "deletions" are ...

**Comment by ThomasLecocq** [comment]
is that so badly written ? :-)

**Comment by megies** [comment]
Not sure what this is doing exactly, but looks great. ;)

**Comment by krischer** [comment]
I guess it kind of slipped under my radar.

As tobi menitioned, Travis fails with a segmentation fault on Python 2.6, 2.7, and 3.3. On Python 3.4 the deconvolution test fails and the arrays do look pretty different.

**Comment by ThomasLecocq** [comment]
beuh...

**Comment by ThomasLecocq** [comment]
so, the segfault doesn't happen on my Windows machine :) And the array stuff, well, I'm not sure of the data I actually compare to... I took some data present in the original folder (src/*) ... but not sure it's the right one. To Check.

**Comment by ThomasLecocq** [comment]
Well, it's not *the* problem, but actually, the if(present( ... )) tests in the original code doens't work... It's also the case for the `mt_coher` test case sets `iadapt` to 1, which is default, and works, by chance, because this:

```fortran
print *, iadapt
   if (present(iadapt)) then 
      if (iadapt == 0) then
         iad = 0
      else
         iad = 1
      endif
   else
      iad = 1
   endif
   print *, iad
```
returns `1`  then `1`. Setting `iadapt` to 0 in the call, returns `0` then `1` again.

In the case of `mt_deconv`, `iadapt` is 0, and gets set to 1 automatically because of the failing `present` call...

tested on both linux & win boxes...

**Comment by ThomasLecocq** [comment]
@krischer could this be resolved with the f2py version ?

**Comment by krischer** [comment]
No I don't think that would be resolved by the f2py. I am also no longer sure if f2py is the way to go as I don't think it is really maintained anymore.

But feel free to change the fortran code in case its necessary (which looks to be the case here). We already modified it in a couple of other places.

**Comment by ThomasLecocq** [comment]
Well, currently I don't really know how to... The key seems to include the subroutine inside a module, so the present() thing works... but then I don't know how to import/use *that* from python ...

Or I could make the arguments **not** optional and remove the present() checks...

**Comment by krischer** [comment]
:+1: Making it non-optional seems very reasonable to me. You can make it optional again on the Python side. The version of mtspecf90 we use here is not developed anymore so I think its fine to make changes to it.

**Comment by ThomasLecocq** [comment]
sounds good to me too then :) Yalla !

**Comment by ThomasLecocq** [comment]
Well, guys, if you have any idea... I'm lost ! :)

figure_1

This figure shows the comparison between the new calculations and the reference data in German's outputs. The difference is dependant of the time, and rapidly goes below the precision of the float32. What is fantastic is this: **starting at index [1], every second point of the two traces are absolutely equal**, (new[1::2] == prieto[1::2]) ... But the [0::2] aren't !

```sh
(mismatch 50.0%)
 x: array([-0.01812, -0.00274, -0.00167, -0.00014,  0.02048,  0.05361,
        0.01864, -0.0194 , -0.01478, -0.01276, -0.00319, -0.01593,
       -0.04574,  0.00272,  0.06735,  0.01352, -0.05917, -0.04215,
        0.01169,  0.04176])
 y: array([-0.01426, -0.00274, -0.00038, -0.00014,  0.02125,  0.05361,
        0.01919, -0.0194 , -0.01435, -0.01276, -0.00284, -0.01593,
       -0.04544,  0.00272,  0.0676 ,  0.01352, -0.05894, -0.04215,
        0.01189,  0.04176], dtype=float32)
```

**Comment by krischer** [comment]
After a *tiny* delay I tackled this - a working version of this is now in the master and in version 0.3.2 :-)

http://krischer.github.io/mtspec/tutorial.html#fig-6-deconvolution

Turns out a couple of other parameters where also affected from the Fortran `present` statement.

**Pull request closed without merging**
